name: Python Development Check
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
jobs:
  uv-setup:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install dependencies
        run: uv sync --dev

      - name: "Run ruff format"
        run: uvx ruff format

      - name: "Run ruff check"
        run: uvx ruff check

      - name: "Run ty"
        run: uvx ty check